import type { FactIcon } from "@/domain/rules";
import type { Lang } from "@/domain/types";

const fr = {
  brand: {
    tagline: "la banque qui bouge avec vous",
    noLlm: "Règles + scripts approuvés · aucun LLM",
    offline: "Serveur injoignable, nouvel essai…",
    language: "Langue",
  },
  stage: {
    steps: {
      event: "Événement",
      situation: "Situation",
      meeSpeaks: "Mee parle",
      customerReplies: "Lotte répond",
      handoff: "Transfert à Anouk",
      why: "Pourquoi ?",
      pause: "Pause",
    },
    simulator: "Simulateur",
    simulatorSub: "Flux d'événements fictifs",
    customer: "Cliente · app mobile",
    customerSub: "Lotte Peeters, Gent",
    agent: "Poste conseiller",
    agentSub: "Centre de contact, même situation",
    openCustomer: "Cliente",
    openAgent: "Conseiller",
  },
  customer: {
    greeting: "Bonjour Lotte",
    checking: "Compte à vue",
    available: "Solde disponible",
    recent: "Activité récente",
    noActivity: "Pas encore d'activité. Lancez un événement depuis le simulateur.",
    promoTitle: "Épargne d'été, taux de base 2,5 %",
    promoBody: "Ouvrez une tirelire en deux gestes.",
    marketingMuted: "Offres en pause 72 h, le temps de souffler",
    muted: "coupé",
    meeOn: "Mee actif",
    meePaused: "Mee en pause",
    meeNow: "Mee · maintenant",
    meeBecause: "Mee · suite à ce qui vient de se passer",
    why: "Pourquoi je vois ceci ?",
    pauseThis: "Mettre en pause",
    listen: "Écouter",
    playing: "Lecture…",
    loadingVoice: "Chargement de la voix…",
    voiceEleven: "Voix ElevenLabs · script approuvé",
    voiceMock: "Voix du navigateur (démo) · script approuvé",
    voiceUnavailable: "Pas de voix dans ce navigateur · ajoutez une clé ElevenLabs",
    whyTitle: "Pourquoi vous voyez ceci",
    weNoticed: "Ce que nous avons remarqué",
    signalsUsed: "Signaux utilisés",
    neverUsed: "Ce que nous n'utilisons jamais",
    ruleLabel: "Règle",
    playbookLabel: "Script",
    expires: "Disparaît tout seul",
    privacy: "Vie privée",
    pauseMee: "Mettre Mee en pause partout",
    pauseMeeHint: "Aucune suggestion dans l'app, par la voix ou au téléphone.",
    pauseType: "Mettre en pause cette situation uniquement",
    pauseNamed: (label: string) => `Mettre « ${label} » en pause`,
    close: "Fermer",
    resolvedToast: "C'est réglé. Mee se fait discret.",
    dismissedToast: "Compris. Nous ne l'afficherons plus.",
    notNowToast: "D'accord. On en reste là pour l'instant.",
    pausedBanner: "Mee est en pause. Vous ne recevrez aucune suggestion.",
    resume: "Réactiver",
    settings: "Réglages Mee",
    settingsIntro: "Mee n'utilise que des signaux que vous attendez de votre banque, et ne montre chaque situation qu'une seule fois.",
    dismissedForever: "Masqué définitivement",
    none: "Aucun",
    home: "Accueil",
    pay: "Payer",
    cards: "Cartes",
    more: "Plus",
    unreachable: (e: string) => `Impossible de joindre le serveur Mee (${e}).`,
    yesterday: "Hier",
    monday: "lun.",
    declined: "Bancontact · refusé",
    salary: "Salaire",
    rent: "Loyer · ordre permanent",
    cardBlocked: (city: string) => `Carte bloquée · ${city}`,
  },
  call: {
    title: "Mee · appel vocal",
    agentTitle: "Anouk · conseillère",
    mee: "Mee",
    agent: "Anouk",
    transcribed: "transcrit",
    quickReply: "réponse rapide",
    tapToTalk: "Touchez pour parler",
    listening: "Je vous écoute… touchez pour envoyer",
    transcribing: "Transcription…",
    micUnavailable: "Micro indisponible ici · touchez une réponse ci-dessous",
    micDenied: "Accès au micro refusé · touchez une réponse ci-dessous",
    heardNothing: "Je n'ai rien entendu. Réessayez ou touchez une réponse.",
    sttEleven: "Transcription ElevenLabs",
    sttOpenai: "Transcription Whisper",
    sttBrowser: "Reconnaissance vocale du navigateur",
    keywordsOnly: "Mee reconnaît des mots-clés approuvés. Aucune IA ne décide.",
    quickReplies: "Ou touchez une réponse",
    toAgent: "Parler à un conseiller",
    hangUp: "Raccrocher",
    handingOff: "Anouk prend l'appel… elle sait déjà tout",
    withAgent: "En ligne avec Anouk",
    agentKnows: "Anouk voit la même situation. Rien à réexpliquer.",
    ended: "Appel terminé",
    endedResolved: "C'est réglé. Mee se fait discret.",
    endedOther: "Vous pouvez rappeler Mee à tout moment.",
    back: "Retour à l'app",
  },
  agent: {
    waiting: "En attente d'un appel",
    knowsNothing: "Mee n'a rien remarqué pour Lotte. C'est voulu : il ne parle que quand une règle matche.",
    knows: (label: string, rule: string, ago: string) => `Mee suit déjà « ${label} » (${rule}), ${ago}.`,
    lastCallMee: "Dernier appel : réglé par Mee, sans conseiller.",
    lastCallAgent: "Dernier appel : réglé par Anouk.",
    lastCallOther: "Dernier appel : raccroché.",
    meeOnLine: "Mee est en ligne avec Lotte",
    meeOnLineSub: "Rien à faire. Si Lotte demande quelqu'un, l'appel arrive ici avec tout le contexte.",
    incoming: "Appel entrant · Lotte Peeters",
    incomingSub: "Transférée par Mee · contexte déjà chargé",
    detected: (ago: string) => `Détecté ${ago}`,
    agoNow: "à l'instant",
    agoMin: (n: number) => `il y a ${n} min`,
    recommended: "Action recommandée :",
    say: "À dire",
    replay: "Réécouter",
    dontAsk: "Ne pas redemander",
    sawHeard: "Ce que Lotte a vu et entendu",
    inApp: "Dans l'app",
    onCall: "Au téléphone avec Mee",
    history: "Historique",
    resolved: "Résolu",
    closeCall: "Clôturer l'appel",
    topics: {
      place: "Où elle se trouve",
      card: "Quelle carte",
      merchant: "Le commerçant",
      amount: "Le montant",
      code: "Le code de refus",
      salary: "Son salaire",
      balance: "Son solde",
      muted: null,
      clean: null,
    } as Record<FactIcon, string | null>,
  },
  sim: {
    j1: "Parcours 1 · Paiement refusé",
    j1Hint: "2 refus Bancontact en 10 min",
    decline: "Refus chez Delhaize",
    declineTwice: "Refus ×2",
    declinesInWindow: "Refus dans la fenêtre :",
    resolveJ1: "Résoudre : le paiement passe",
    j2: "Parcours 2 · Fin de mois serrée",
    j2Hint: "salaire → loyer → solde sous 150 €",
    salary: "Salaire",
    rent: "Loyer",
    low: "Solde bas",
    playPattern: "Jouer le scénario complet",
    resolveJ2: "Résoudre : le solde remonte",
    j3: "Parcours 3 · Carte bloquée",
    j3Hint: "carte bloquée hors de Belgique",
    blockAbroad: "Carte bloquée à Lisbonne",
    blockHome: "Contrôle : bloquée à Gent",
    resolveJ3: "Résoudre : carte débloquée",
    contrast: "Contraste : ancien serveur vocal",
    contrastHint: "ce que Lotte entendait avant Mee",
    shortcuts: "Raccourcis cliente",
    shortcutsHint: "comme un geste dans l'app",
    dismiss: "Écarter la situation active",
    rules: "Règles en veille",
    rulesHint: "déterministes, versionnées, sans modèle",
    reset: "Réinitialiser la démo",
    ruleDismissed: "masquée ∞",
    rulePaused: "en pause",
    ruleFiring: "active",
    ruleArmed: "armée",
  },
};

export type Copy = typeof fr;

const nl: Copy = {
  brand: {
    tagline: "de bank die met je meebeweegt",
    noLlm: "Regels + goedgekeurde scripts · geen LLM",
    offline: "Server onbereikbaar, opnieuw proberen…",
    language: "Taal",
  },
  stage: {
    steps: {
      event: "Event",
      situation: "Situatie",
      meeSpeaks: "Mee spreekt",
      customerReplies: "Lotte antwoordt",
      handoff: "Doorverbinden naar Anouk",
      why: "Waarom?",
      pause: "Pauze",
    },
    simulator: "Simulator",
    simulatorSub: "Nagebootste eventstroom",
    customer: "Klant · mobiele app",
    customerSub: "Lotte Peeters, Gent",
    agent: "Agentenscherm",
    agentSub: "Contactcenter, dezelfde situatie",
    openCustomer: "Klant",
    openAgent: "Agent",
  },
  customer: {
    greeting: "Goeiemiddag, Lotte",
    checking: "Zichtrekening",
    available: "Beschikbaar saldo",
    recent: "Recente activiteit",
    noActivity: "Nog geen nieuwe activiteit. Stuur een event vanuit de simulator.",
    promoTitle: "Zomersparen, 2,5% basisrente",
    promoBody: "Open een spaarpotje in twee tikken.",
    marketingMuted: "Aanbiedingen 72 u gepauzeerd terwijl je weer op adem komt",
    muted: "gedempt",
    meeOn: "Mee aan",
    meePaused: "Mee gepauzeerd",
    meeNow: "Mee · nu",
    meeBecause: "Mee · door wat er net gebeurde",
    why: "Waarom zie ik dit?",
    pauseThis: "Pauzeer",
    listen: "Luister",
    playing: "Speelt af…",
    loadingVoice: "Stem laden…",
    voiceEleven: "Stem via ElevenLabs · goedgekeurd script",
    voiceMock: "Browserstem (mock) · goedgekeurd script",
    voiceUnavailable: "Geen stem in deze browser · voeg een ElevenLabs-sleutel toe",
    whyTitle: "Waarom je dit ziet",
    weNoticed: "We merkten",
    signalsUsed: "Signalen die we gebruikten",
    neverUsed: "Wat we nooit gebruiken",
    ruleLabel: "Regel",
    playbookLabel: "Script",
    expires: "Dit verdwijnt vanzelf",
    privacy: "Privacy-instellingen",
    pauseMee: "Pauzeer Mee overal",
    pauseMeeHint: "Geen nudges in de app, via spraak of aan de telefoon.",
    pauseType: "Pauzeer enkel deze situatie",
    pauseNamed: (label) => `Pauzeer “${label}”`,
    close: "Sluiten",
    resolvedToast: "Opgelost. Mee wordt weer stil.",
    dismissedToast: "Begrepen. We tonen dit niet meer.",
    notNowToast: "Oké. We laten het even rusten.",
    pausedBanner: "Mee is gepauzeerd. Je krijgt geen nudges.",
    resume: "Hervat",
    settings: "Mee-instellingen",
    settingsIntro: "Mee gebruikt enkel signalen die je van je bank verwacht, en toont elke situatie maximaal één keer.",
    dismissedForever: "Voorgoed verborgen",
    none: "Geen",
    home: "Home",
    pay: "Betalen",
    cards: "Kaarten",
    more: "Meer",
    unreachable: (e) => `Kan de Mee-server niet bereiken (${e}).`,
    yesterday: "Gisteren",
    monday: "ma",
    declined: "Bancontact · geweigerd",
    salary: "Loon",
    rent: "Huur · doorlopende opdracht",
    cardBlocked: (city) => `Kaart geblokkeerd · ${city}`,
  },
  call: {
    title: "Mee · spraakoproep",
    agentTitle: "Anouk · adviseur",
    mee: "Mee",
    agent: "Anouk",
    transcribed: "getranscribeerd",
    quickReply: "snel antwoord",
    tapToTalk: "Tik om te spreken",
    listening: "Ik luister… tik om te versturen",
    transcribing: "Transcriberen…",
    micUnavailable: "Geen microfoon hier · tik een antwoord hieronder",
    micDenied: "Microfoon geweigerd · tik een antwoord hieronder",
    heardNothing: "Ik hoorde niets. Probeer opnieuw of tik een antwoord.",
    sttEleven: "Transcriptie ElevenLabs",
    sttOpenai: "Transcriptie Whisper",
    sttBrowser: "Spraakherkenning van de browser",
    keywordsOnly: "Mee herkent goedgekeurde trefwoorden. Geen AI beslist.",
    quickReplies: "Of tik een antwoord",
    toAgent: "Spreek een adviseur",
    hangUp: "Ophangen",
    handingOff: "Anouk neemt op… ze weet al alles",
    withAgent: "In gesprek met Anouk",
    agentKnows: "Anouk ziet dezelfde situatie. Niets opnieuw uitleggen.",
    ended: "Gesprek beëindigd",
    endedResolved: "Opgelost. Mee wordt weer stil.",
    endedOther: "Je kan Mee altijd opnieuw bellen.",
    back: "Terug naar de app",
  },
  agent: {
    waiting: "Wachten op een oproep",
    knowsNothing: "Mee merkte niets op bij Lotte. Dat is de bedoeling: Mee spreekt pas als een regel matcht.",
    knows: (label, rule, ago) => `Mee volgt al “${label}” (${rule}), ${ago}.`,
    lastCallMee: "Laatste oproep: opgelost door Mee, zonder adviseur.",
    lastCallAgent: "Laatste oproep: opgelost door Anouk.",
    lastCallOther: "Laatste oproep: opgehangen.",
    meeOnLine: "Mee is in gesprek met Lotte",
    meeOnLineSub: "Niets te doen. Vraagt Lotte naar iemand, dan komt de oproep hier binnen met alle context.",
    incoming: "Inkomende oproep · Lotte Peeters",
    incomingSub: "Doorverbonden door Mee · context al geladen",
    detected: (ago) => `Gedetecteerd ${ago}`,
    agoNow: "net nu",
    agoMin: (n) => `${n} min geleden`,
    recommended: "Aanbevolen actie:",
    say: "Te zeggen",
    replay: "Opnieuw beluisteren",
    dontAsk: "Niet opnieuw vragen",
    sawHeard: "Wat Lotte zag en hoorde",
    inApp: "In de app",
    onCall: "Aan de lijn met Mee",
    history: "Geschiedenis",
    resolved: "Opgelost",
    closeCall: "Oproep afsluiten",
    topics: {
      place: "Waar ze is",
      card: "Welke kaart",
      merchant: "De handelaar",
      amount: "Het bedrag",
      code: "De weigeringscode",
      salary: "Haar loon",
      balance: "Haar saldo",
      muted: null,
      clean: null,
    },
  },
  sim: {
    j1: "Traject 1 · Betaling mislukt",
    j1Hint: "2 Bancontact-weigeringen binnen 10 min",
    decline: "Weigering bij Delhaize",
    declineTwice: "Weigering ×2",
    declinesInWindow: "Weigeringen in venster:",
    resolveJ1: "Oplossen: betaling lukt",
    j2: "Traject 2 · Krappe maand",
    j2Hint: "loon → huur → saldo onder €150",
    salary: "Loon",
    rent: "Huur",
    low: "Laag saldo",
    playPattern: "Speel volledig patroon",
    resolveJ2: "Oplossen: saldo herstelt",
    j3: "Traject 3 · Kaart geblokkeerd",
    j3Hint: "kaart geblokkeerd buiten België",
    blockAbroad: "Kaart geblokkeerd in Lissabon",
    blockHome: "Controle: geblokkeerd in Gent",
    resolveJ3: "Oplossen: kaart gedeblokkeerd",
    contrast: "Contrast: oude telefooncentrale",
    contrastHint: "wat Lotte vroeger hoorde",
    shortcuts: "Snelkoppelingen klant",
    shortcutsHint: "zoals tikken in de app",
    dismiss: "Actieve situatie wegklikken",
    rules: "Regels op wacht",
    rulesHint: "deterministisch, geversioneerd, geen model",
    reset: "Demo resetten",
    ruleDismissed: "verborgen ∞",
    rulePaused: "gepauzeerd",
    ruleFiring: "actief",
    ruleArmed: "paraat",
  },
};

const en: Copy = {
  brand: {
    tagline: "the bank that moves with you",
    noLlm: "Rules + approved scripts · no LLM",
    offline: "Server unreachable, retrying…",
    language: "Language",
  },
  stage: {
    steps: {
      event: "Event",
      situation: "Situation",
      meeSpeaks: "Mee speaks",
      customerReplies: "Lotte replies",
      handoff: "Handoff to Anouk",
      why: "Why?",
      pause: "Pause",
    },
    simulator: "Simulator",
    simulatorSub: "Mock event stream",
    customer: "Customer · mobile app",
    customerSub: "Lotte Peeters, Gent",
    agent: "Agent desk",
    agentSub: "Contact center, same situation",
    openCustomer: "Customer",
    openAgent: "Agent",
  },
  customer: {
    greeting: "Good afternoon, Lotte",
    checking: "Current account",
    available: "Available balance",
    recent: "Recent activity",
    noActivity: "No new activity yet. Fire an event from the simulator.",
    promoTitle: "Summer savings, 2.5% base rate",
    promoBody: "Open a savings pot in two taps.",
    marketingMuted: "Offers paused for 72h while you get back on track",
    muted: "muted",
    meeOn: "Mee on",
    meePaused: "Mee paused",
    meeNow: "Mee · now",
    meeBecause: "Mee · because of what just happened",
    why: "Why am I seeing this?",
    pauseThis: "Pause this",
    listen: "Listen",
    playing: "Playing…",
    loadingVoice: "Loading voice…",
    voiceEleven: "Voice by ElevenLabs · approved script",
    voiceMock: "Browser voice (mock) · approved script",
    voiceUnavailable: "No voice in this browser · add an ElevenLabs key",
    whyTitle: "Why you're seeing this",
    weNoticed: "We noticed",
    signalsUsed: "Signals we used",
    neverUsed: "What we never use",
    ruleLabel: "Rule",
    playbookLabel: "Script",
    expires: "This goes away by itself",
    privacy: "Privacy controls",
    pauseMee: "Pause Mee everywhere",
    pauseMeeHint: "No nudges in app, voice or on the phone line.",
    pauseType: "Pause only this situation",
    pauseNamed: (label) => `Pause “${label}”`,
    close: "Close",
    resolvedToast: "Sorted. Mee goes quiet again.",
    dismissedToast: "Got it. We won't show this again.",
    notNowToast: "Okay. We'll leave it for now.",
    pausedBanner: "Mee is paused. You won't get any nudges.",
    resume: "Resume",
    settings: "Mee settings",
    settingsIntro: "Mee only uses signals you'd expect your bank to see, and shows each situation at most once.",
    dismissedForever: "Hidden forever",
    none: "None",
    home: "Home",
    pay: "Pay",
    cards: "Cards",
    more: "More",
    unreachable: (e) => `Can't reach the Mee server (${e}).`,
    yesterday: "Yesterday",
    monday: "Mon",
    declined: "Bancontact · declined",
    salary: "Salary",
    rent: "Rent · standing order",
    cardBlocked: (city) => `Card blocked · ${city}`,
  },
  call: {
    title: "Mee · voice call",
    agentTitle: "Anouk · advisor",
    mee: "Mee",
    agent: "Anouk",
    transcribed: "transcribed",
    quickReply: "quick reply",
    tapToTalk: "Tap to talk",
    listening: "Listening… tap to send",
    transcribing: "Transcribing…",
    micUnavailable: "No microphone here · tap a reply below",
    micDenied: "Microphone blocked · tap a reply below",
    heardNothing: "I didn't hear anything. Try again or tap a reply.",
    sttEleven: "Transcription by ElevenLabs",
    sttOpenai: "Transcription by Whisper",
    sttBrowser: "Browser speech recognition",
    keywordsOnly: "Mee recognises approved keywords. No AI decides.",
    quickReplies: "Or tap a reply",
    toAgent: "Talk to an advisor",
    hangUp: "Hang up",
    handingOff: "Anouk is picking up… she already knows everything",
    withAgent: "On the line with Anouk",
    agentKnows: "Anouk sees the same situation. Nothing to re-explain.",
    ended: "Call ended",
    endedResolved: "Sorted. Mee goes quiet again.",
    endedOther: "You can call Mee again any time.",
    back: "Back to the app",
  },
  agent: {
    waiting: "Waiting for a call",
    knowsNothing: "Mee hasn't noticed anything for Lotte. That's the point: it only speaks when a rule matches.",
    knows: (label, rule, ago) => `Mee is already tracking “${label}” (${rule}), ${ago}.`,
    lastCallMee: "Last call: sorted by Mee, no advisor needed.",
    lastCallAgent: "Last call: sorted by Anouk.",
    lastCallOther: "Last call: hung up.",
    meeOnLine: "Mee is on the line with Lotte",
    meeOnLineSub: "Nothing to do. If Lotte asks for someone, the call lands here with the full context.",
    incoming: "Incoming call · Lotte Peeters",
    incomingSub: "Handed over by Mee · context already loaded",
    detected: (ago) => `Detected ${ago}`,
    agoNow: "just now",
    agoMin: (n) => `${n} min ago`,
    recommended: "Recommended action:",
    say: "Say this",
    replay: "Replay",
    dontAsk: "Don't re-ask",
    sawHeard: "What Lotte saw and heard",
    inApp: "In the app",
    onCall: "On the phone with Mee",
    history: "History",
    resolved: "Resolved",
    closeCall: "Close the call",
    topics: {
      place: "Where she is",
      card: "Which card",
      merchant: "The merchant",
      amount: "The amount",
      code: "The decline code",
      salary: "Her salary",
      balance: "Her balance",
      muted: null,
      clean: null,
    },
  },
  sim: {
    j1: "Journey 1 · Payment fail",
    j1Hint: "2 Bancontact declines within 10 min",
    decline: "Decline at Delhaize",
    declineTwice: "Decline ×2",
    declinesInWindow: "Declines in window:",
    resolveJ1: "Resolve: payment goes through",
    j2: "Journey 2 · Cash stress",
    j2Hint: "salary → rent → balance under €150",
    salary: "Salary",
    rent: "Rent",
    low: "Low",
    playPattern: "Play full pattern",
    resolveJ2: "Resolve: balance recovers",
    j3: "Journey 3 · Card blocked",
    j3Hint: "card blocked outside Belgium",
    blockAbroad: "Card blocked in Lisbon",
    blockHome: "Control: blocked in Gent",
    resolveJ3: "Resolve: card unblocked",
    contrast: "Contrast: old phone menu",
    contrastHint: "what Lotte heard before Mee",
    shortcuts: "Customer shortcuts",
    shortcutsHint: "same as tapping in the app",
    dismiss: "Dismiss active situation",
    rules: "Rules watching",
    rulesHint: "deterministic, versioned, no model",
    reset: "Reset demo",
    ruleDismissed: "dismissed ∞",
    rulePaused: "paused",
    ruleFiring: "firing",
    ruleArmed: "armed",
  },
};

export const COPY: Record<Lang, Copy> = { fr, nl, en };

const LOCALE: Record<Lang, string> = { fr: "fr-BE", nl: "nl-BE", en: "en-GB" };

export const fmtEur = (n: number, lang: Lang) => new Intl.NumberFormat(LOCALE[lang], { style: "currency", currency: "EUR" }).format(n);

export const fmtTime = (ms: number, lang: Lang) =>
  new Intl.DateTimeFormat(LOCALE[lang], { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(ms);

export const fmtUntil = (ms: number, lang: Lang) => new Intl.DateTimeFormat(LOCALE[lang], { weekday: "short", hour: "2-digit", minute: "2-digit" }).format(ms);

export const fmtClock = (ms: number) => {
  const s = Math.max(0, Math.floor(ms / 1000));
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;
};

export const fmtAgo = (ms: number, lang: Lang) => {
  const min = Math.floor(ms / 60_000);
  return min < 1 ? COPY[lang].agent.agoNow : COPY[lang].agent.agoMin(min);
};
