import type { Lang } from "@/domain/types";

const en = {
  greeting: "Good afternoon, Lotte",
  checking: "Current account",
  available: "Available balance",
  recent: "Recent activity",
  noActivity: "No new activity yet. Fire an event from the simulator.",
  promoTitle: "Summer savings, 2.5% base rate",
  promoBody: "Open a savings pot in two taps.",
  marketingMuted: "Offers paused for 72h while you get back on track",
  meeOn: "Mee on",
  meePaused: "Mee paused",
  meeNow: "Mee · now",
  meeBecause: "Mee · because of what just happened",
  why: "Why am I seeing this?",
  pauseThis: "Pause this type",
  listen: "Listen",
  playing: "Playing…",
  loadingVoice: "Loading voice…",
  voiceEleven: "Voice by ElevenLabs · approved script",
  voiceMock: "Browser voice (mock) · approved script",
  voiceUnavailable: "No voice in this browser · add an ElevenLabs key",
  whyTitle: "Why you're seeing this",
  weNoticed: "We noticed",
  signalsUsed: "Signals we used",
  neverUsed: "What we never use",
  ruleLabel: "Rule",
  playbookLabel: "Script",
  expires: "This goes away by itself",
  privacy: "Privacy controls",
  pauseMee: "Pause Mee everywhere",
  pauseMeeHint: "No nudges in app, voice or on the phone line.",
  pauseType: "Pause only this situation",
  close: "Close",
  resolvedToast: "Sorted. Mee goes quiet again.",
  dismissedToast: "Got it. We won't show this again.",
  notNowToast: "Okay. We'll leave it for now.",
  onCall: "On the line with support",
  onCallBody: "Anouk already sees what happened. No need to explain again.",
  pausedBanner: "Mee is paused. You won't get any nudges.",
  resume: "Resume",
  settings: "Mee settings",
  dismissedForever: "Hidden forever",
  none: "None",
  home: "Home",
  pay: "Pay",
  cards: "Cards",
  more: "More",
};

export type Copy = typeof en;

const nl: Copy = {
  greeting: "Goeiemiddag, Lotte",
  checking: "Zichtrekening",
  available: "Beschikbaar saldo",
  recent: "Recente activiteit",
  noActivity: "Nog geen nieuwe activiteit. Stuur een event vanuit de simulator.",
  promoTitle: "Zomersparen, 2,5% basisrente",
  promoBody: "Open een spaarpotje in twee tikken.",
  marketingMuted: "Aanbiedingen 72 u gepauzeerd terwijl je weer op adem komt",
  meeOn: "Mee aan",
  meePaused: "Mee gepauzeerd",
  meeNow: "Mee · nu",
  meeBecause: "Mee · door wat er net gebeurde",
  why: "Waarom zie ik dit?",
  pauseThis: "Pauzeer dit type",
  listen: "Luister",
  playing: "Speelt af…",
  loadingVoice: "Stem laden…",
  voiceEleven: "Stem via ElevenLabs · goedgekeurd script",
  voiceMock: "Browserstem (mock) · goedgekeurd script",
  voiceUnavailable: "Geen stem in deze browser · voeg een ElevenLabs-sleutel toe",
  whyTitle: "Waarom je dit ziet",
  weNoticed: "We merkten",
  signalsUsed: "Signalen die we gebruikten",
  neverUsed: "Wat we nooit gebruiken",
  ruleLabel: "Regel",
  playbookLabel: "Script",
  expires: "Dit verdwijnt vanzelf",
  privacy: "Privacy-instellingen",
  pauseMee: "Pauzeer Mee overal",
  pauseMeeHint: "Geen nudges in de app, via spraak of aan de telefoon.",
  pauseType: "Pauzeer enkel deze situatie",
  close: "Sluiten",
  resolvedToast: "Opgelost. Mee wordt weer stil.",
  dismissedToast: "Begrepen. We tonen dit niet meer.",
  notNowToast: "Oké. We laten het even rusten.",
  onCall: "In gesprek met support",
  onCallBody: "Anouk ziet al wat er gebeurde. Je hoeft niets opnieuw uit te leggen.",
  pausedBanner: "Mee is gepauzeerd. Je krijgt geen nudges.",
  resume: "Hervat",
  settings: "Mee-instellingen",
  dismissedForever: "Voorgoed verborgen",
  none: "Geen",
  home: "Home",
  pay: "Betalen",
  cards: "Kaarten",
  more: "Meer",
};

export const COPY: Record<Lang, Copy> = { en, nl };

export const fmtEur = (n: number, lang: Lang) =>
  new Intl.NumberFormat(lang === "nl" ? "nl-BE" : "en-BE", { style: "currency", currency: "EUR" }).format(n);

export const fmtTime = (ms: number, lang: Lang) =>
  new Intl.DateTimeFormat(lang === "nl" ? "nl-BE" : "en-GB", { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(ms);

export const fmtUntil = (ms: number, lang: Lang) =>
  new Intl.DateTimeFormat(lang === "nl" ? "nl-BE" : "en-GB", { weekday: "short", hour: "2-digit", minute: "2-digit" }).format(ms);
